os: osx
language: ruby
addons:
  chrome: stable
  homebrew:
    packages:
    - postgresql
    - redis
    - yarn
    casks:
    - chromedriver
cache:
  - bundler
  - yarn
before_install:
  - gem install bundler
  - nvm install --lts
  - brew services start postgresql
  - brew services start redis
script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:schema:load  
  - bundle exec rake test
  - bundle exec rake test:system
