os: osx
language: ruby
addons:
  chrome: stable
  homebrew:
    packages:
    - postgresql
    - redis
    - yarn
    casks:
    - chromedriver
before_install:
  - nvm install --lts
script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:schema:load  
  - bundle exec rake test
  - bundle exec rake test:system