os: osx
addons:
  chrome: stable
  homebrew:
    packages:
    - postgresql
    - redis
    - yarn
    casks:
    - chromedriver
language: ruby
cache:
  - bundler
  - yarn
before_install:
  - nvm install --lts
script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:migrate  
  - bundle exec rake test
  - bundle exec rake test:system
